### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'initial_amount'

### ISSUE THREAD

**Issue by shintafiaa** [AI4Finance-Foundation/FinRL#518] opened 2022-03-14 02:52 UTC
I got a bug on cell number [18]. Line code number 14 is red underlined. 

here is the code which is red underlined:
e_train_gym = StockTradingEnv(df = train, **env_kwargs)

here is the error warning:
TypeError                                 Traceback (most recent call last)
[<ipython-input-18-c60f10b3a745>](https://localhost:8080/#) in <module>()
     12 }
     13 
---> 14 e_train_gym = StockTradingEnv(df = train, **env_kwargs)

TypeError: __init__() got an unexpected keyword argument 'initial_amount'

How to solve this bug? thank's before.

**Comment by ObaidaAlhaasan** [comment] 2022-03-14 12:18
Hi team,

I got the same error and when I commented out the initial_amount line of code I got

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-52-6f99a2a2ef8c>](https://localhost:8080/#) in <module>()
     12 }
     13 
---> 14 e_train_gym = StockTradingEnv(df = train, **env_kwargs)

TypeError: __init__() missing 1 required positional argument: 'initial_list'
```

And in the source code, I saw that the Initial_amount is commented out, is it as simple as un-comment that line? If so I would be happy to submit a PR
[Commented out initial_amount line of code](https://github.com/AI4Finance-Foundation/FinRL/blob/2adc865ff6aea1f7a92ecd251da98c2c2bac3f18/finrl/finrl_meta/env_stock_trading/env_stocktrading.py#L26)

**Comment by ObaidaAlhaasan** [comment] 2022-03-14 12:43
I see, there is a PR to revert the change that commented initial_amount
[PR LINK](https://github.com/AI4Finance-Foundation/FinRL/pull/497)

**Comment by NorthKoreaBestKorea** [comment] 2022-03-14 16:18
Trying to get started and cant run the initial notebook because of  this error.

**Comment by dpaiton** [comment] 2022-03-17 22:56
This was also discussed a while back here: https://github.com/AI4Finance-Foundation/FinRL/issues/495

It was closed, but there is still a problem to be addressed.

**Comment by Neogohan1** [comment] 2022-03-19 01:51
> 

Using this change I did manage to run the next few lines but when trying to train_model i get

TypeError: 'float' object is not subscriptable 

Seems to be caused by something on

available_amount = self.state[0] / (self.state[index + 1]*(1 + self.buy_cost_pct[index]))

Any ideas?

**Comment by Yaotian-Liu** [comment] 2022-03-22 11:08
I have submit a [PR](https://github.com/AI4Finance-Foundation/FinRL/pull/532#issue-1174884923) which has been merged and fix this bug in `tutorials/1-Introduction/FinRL_StockTrading_NeurIPS_2018.ipynb`

**Comment by zhumingpassional** [comment] 2022-03-28 08:16
developpers updated the code today: add the num_stock_shares, which should be initialized as [0] * stock_dimension

**Comment by zhumingpassional** [comment] 2022-03-28 09:20
"initial_amount" should be set 1000000

**Comment by PierrickI3** [comment] 2022-03-28 09:23
That works. Thanks!

**Comment by zhumingpassional** [comment] 2022-03-29 02:02
@PierrickI3  Could you push a PR for this problem?

**Comment by zhumingpassional** [comment] 2022-03-29 14:59
Fixed. Thanks.

**Closed** 2022-04-04 10:17 UTC
Labels: bug

**Comment by flyingsandwich1** [comment] 2022-04-16 05:59
> Not sure how I can do that.
> 
> Here is the final version of my `Trade Data Split` step which works:
> 
> ```
> buy_cost_list = sell_cost_list = [0.001] * stock_dimension
> num_stock_shares = [0] * stock_dimension
> 
> env_kwargs = { 
>     "hmax": 100, 
>     "initial_amount": 1000000, 
>     "num_stock_shares": num_stock_shares,
>     "buy_cost_pct": buy_cost_list, 
>     "sell_cost_pct": sell_cost_list, 
>     "state_space": state_space, 
>     "stock_dim": stock_dimension, 
>     "tech_indicator_list": config.INDICATORS, 
>     "action_space": stock_dimension, 
>     "reward_scaling": 1e-4 
> }
> e_train_gym = StockTradingEnv(df = train, **env_kwargs)
> ```

Where did you put this in the code? I'm having issues where it says:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\Trader\MultipleStockTrader.py", line 453, in <module>
    buy_cost_list = sell_cost_list = [0.001] * stock_dim
NameError: name 'stock_dim' is not defined

Would really appreciate the help! I'm a beginner :)

**Comment by zhumingpassional** [comment] 2022-04-17 06:39
@flyingsandwich1  which notebook did you run?  Have you revised anything?
