### ISSUE TITLE
help to resolve ERORR

### ISSUE THREAD

**Issue by skhonsha** [AI4Finance-Foundation/FinRL#436] opened 2022-01-20 12:55 UTC
Hi,
Thank you in advance for any help on resolve this error.
![eeeee](https://user-images.githubusercontent.com/40491703/150342646-01183d93-59d2-4dfa-8bd1-4dcc4837e06c.png)

**Comment by Athe-kunal** [comment] 2022-01-20 13:52
This is an expected behaviour in hyperparameter optimization. The model may diverge due to bad hyperparameters. That's why we have the catch parameter to continue even if you encounter ValueError. Just make sure that you have good dataset with no missing values

**Comment by skhonsha** [comment] 2022-01-20 16:24
@Athe-kunal  thank you, all trials had this error!, I insert NaN handler commands and worked.

**Comment by Athe-kunal** [comment] 2022-01-20 19:05
That's great @skhonsha . I am closing this issue, if you have further questions, do re-open

**Closed by Athe-kunal** 2022-01-20 19:05 UTC
Labels: bug
